#!/usr/bin/env bash
# Enables management via the init script and also
# Distributes requests using round-robin algorithm
# Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get install -y haproxy

echo "ENABLED-1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
touch /etc/haproxy/haproxy.cfg

printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	option httplog
	option dontlognull
	retries 3
	option redispatch
	timeout connect 5000
	timeout client 30000
	timeout	server 30000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
	timeout client 30000
	bind	0:80
	default_backend servers

backend servers
	timeout connect 3000
	timeout connect 30000
	balance roundrobin
	server 530724-web-01 18.206.232.255.80 check
	server 530724-web-02 18.234.107.26.80 check

- >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
