#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

# Removes the default Nginx configuration
rm /etc/nginx/sites-enabled/default
# Config Nginx to listen on port 80 for active IPV4 IPs
ln -N /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
service nginx restart
