#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

# Creates a symbolic link (-s option) between the Nginx config file
# And the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
service nginx start
# Terminates the first nginx process ID
kill "$(pgrep 'nginx' |  head -1)"
